## Numpy: Numeric computing library

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays


In [1]:
import numpy as np

### Basic Numpy Arrays 

In [18]:
# create array
a = np.array([1,2,3,4], dtype=np.int8)

# a[start:stop:step]

In [20]:
a[1:]

array([2, 3, 4], dtype=int8)

In [21]:
a[0:2]

array([1, 2], dtype=int8)

In [22]:
a[1:-2]

array([2], dtype=int8)

In [23]:
a[::3]

array([1, 4], dtype=int8)

In [19]:
a[[0, 2, -1]] # another array   

array([1, 3, 4], dtype=int8)